// <auto-generated />
using System;
using HubCount.Urna.Core.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HubCount.Urna.Core.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20220718213421_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HubCount.Urna.Core.Models.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CANDIDATE_NAME");

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_CREATE");

                    b.Property<decimal>("Legenda")
                        .HasColumnType("DECIMAL(2,0)")
                        .HasColumnName("lEGENDA");

                    b.Property<string>("ViceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("VICE_NAME");

                    b.HasKey("Id");

                    b.ToTable("TB_CANDIDATE", (string)null);
                });

            modelBuilder.Entity("HubCount.Urna.Core.Models.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int")
                        .HasColumnName("CANDIDATE_ID");

                    b.Property<DateTime>("DtVote")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DT_VOTE");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("TB_VOTE", (string)null);
                });

            modelBuilder.Entity("HubCount.Urna.Core.Models.Entities.Vote", b =>
                {
                    b.HasOne("HubCount.Urna.Core.Models.Entities.Candidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("HubCount.Urna.Core.Models.Entities.Candidate", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
